/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Control-QuickTime-Player.h
 #	source generated by 4D Plugin Wizard
 #	Project : Control QuickTime Player
 #	author : miyako
 #	2022/03/04
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CONTROL_QUICKTIME_PLAYER_H
#define PLUGIN_CONTROL_QUICKTIME_PLAYER_H

#include "4DPluginAPI.h"
#include "4DPlugin-Control-QuickTime-Player.h"
#include "4DPlugin-JSON.h"
#import <objc/runtime.h>
#import <AppKit/AppKit.h>

#pragma mark -

void QuickTime_Player_Execute(PA_PluginParameters params);

#endif /* PLUGIN_CONTROL_QUICKTIME_PLAYER_H */
