/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Control-QuickTime-Player.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Control QuickTime Player
 #	author : miyako
 #	2022/03/04
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Control-QuickTime-Player.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Control QuickTime Player
            
			case 1 :
				QuickTime_Player_Execute(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void QuickTime_Player_Execute(PA_PluginParameters params) {

}

